const PANELS = {
  FETCH: "FETCH_PANELS",
  FETCH_SUCCESS: "FETCH_PANELS_SUCCESS",
  FETCH_FAIL: "FETCH_PANELS_FAIL",
  COUNT_IMPRESSION: "COUNT_IMPRESSION",
  RESET_IMPRESSIONS: "RESET_IMPRESSIONS",
};

const THEME = {
  CHANGE: "THEME_CHANGE",
};

const INDEX_ARTICLES = {
  FETCH: "INDEX_ARTICLES_FETCH",
  FETCH_MORE: "INDEX_ARTICLES_FETCH_MORE",
  FETCH_SUCCESS: "INDEX_ARTICLES_FETCH_SUCCESS",
  FETCH_FAIL: "INDEX_ARTICLES_FETCH_FAIL",
};

const ARCHIVE_ARTICLES = {
  FETCH: "ARCHIVE_ARTICLES_FETCH",
  FETCH_SUCCESS_CLIENT: "ARCHIVE_ARTICLES_FETCH_SUCCESS",
  FETCH_SUCCESS_SERVER: "ARCHIVE_ARTICLES_FETCH_SUCCESS_SERVER",
  FETCH_FAIL: "ARCHIVE_ARTICLES_FETCH_FAIL",
};

export { PANELS, THEME, INDEX_ARTICLES, ARCHIVE_ARTICLES };
